### ISSUE TITLE
Support min and max in FletcherArray._reduce

### ISSUE THREAD

**Issue by krivonogov** [tinyclues/fletcher#18]
Currently, min and max are not supported:
```python
df = pd.DataFrame({'int': fr.FletcherArray([1, 2, 3])})
df['int'].max()
```
will raise.

We want to support `name='min'/'max'` in `FletcherArray._reduce`. As usual, we shouldn't pass by pandas for it and stay in pyarrow runtime, but `pa.Array` doesn't implement `min`/`max` functions, so maybe we can try to work directly with buffer.

Other way is to check how `pa.Array.sum` is implemented (it is branched from C) and check if there is already C-level method for min/max

**Comment by marc9595** [comment]
I tackle this in https://github.com/tinyclues/fletcher/pull/21
