### ISSUE TITLE
Benchmark current FetcherArray.isna implementation

### ISSUE THREAD

**Issue by krivonogov** [tinyclues/fletcher#3]

**Comment by krivonogov** [comment]
I made benchmark for arrays of size `10 ** 8` for int, float, string types (with and without list). `FletcherArray.isna` is faster than our naive implementation.

https://github.com/tinyclues/datascience/blob/master/akv/2019_10_16_benchmark_fletcher_isna.ipynb

![Capture d’écran 2019-10-16 à 15 36 35](https://user-images.githubusercontent.com/10052527/66924447-f3bc3000-f02a-11e9-8633-4fc48e559801.png)

@marc9595 you can use this script (data generation + plot) for your timing benchmarks for `take`

**Comment by artemru** [comment]
looks like numba is doing better ...

**Comment by artemru** [comment]
let's close this for now !
